-- Isolated runtime regression for monthly_checkin_notifications.sql.
-- Run only in a disposable PostgreSQL database. Everything is rolled back.

begin;

do $bootstrap$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin;
  end if;
end;
$bootstrap$;

create table public.profiles (
  id uuid primary key,
  email text
);

create table public.push_tokens (
  user_id uuid not null,
  is_active boolean default true
);

create table public.notification_preferences (
  user_id uuid not null,
  daily_digest_enabled boolean default true,
  updated_at timestamptz default now()
);

create table public.scheduled_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  task_id uuid,
  notification_type text not null default 'due_1d',
  scheduled_for timestamptz not null,
  status text not null default 'scheduled'
);

\ir monthly_checkin_notifications.sql

-- Emulate production's old explicit grants. Revoking PUBLIC alone must not
-- count as closing anon/authenticated access after CREATE OR REPLACE.
grant execute on function public.ensure_monthly_checkin_notifications() to anon, authenticated;
\ir monthly_checkin_notifications.sql

insert into public.profiles (id, email)
values
  ('f1000000-0000-4000-8000-000000000001', 'existing@example.test'),
  ('f1000000-0000-4000-8000-000000000002', null),
  ('f1000000-0000-4000-8000-000000000003', 'disabled@example.test'),
  ('f1000000-0000-4000-8000-000000000004', '   '),
  ('f1000000-0000-4000-8000-000000000005', 'latest-enabled@example.test'),
  ('f1000000-0000-4000-8000-000000000006', null);

insert into public.push_tokens (user_id, is_active)
values
  ('f1000000-0000-4000-8000-000000000002', true),
  ('f1000000-0000-4000-8000-000000000006', false);

insert into public.notification_preferences (
  user_id,
  daily_digest_enabled,
  updated_at
)
values
  ('f1000000-0000-4000-8000-000000000003', false, now()),
  ('f1000000-0000-4000-8000-000000000005', false, now() - interval '1 day'),
  ('f1000000-0000-4000-8000-000000000005', true, now());

-- An existing future row for one user must not suppress another user's row.
insert into public.scheduled_notifications (
  user_id,
  task_id,
  notification_type,
  scheduled_for,
  status
)
values (
  'f1000000-0000-4000-8000-000000000001',
  null,
  'monthly_checkin',
  now() + interval '1 day',
  'scheduled'
);

do $regression$
declare
  v_inserted integer;
  v_expected_date date := timezone('Asia/Tokyo', now())::date + 30;
begin
  if has_function_privilege(
       'public',
       'public.ensure_monthly_checkin_notifications()',
       'EXECUTE'
     )
     or has_function_privilege(
       'anon',
       'public.ensure_monthly_checkin_notifications()',
       'EXECUTE'
     )
     or has_function_privilege(
       'authenticated',
       'public.ensure_monthly_checkin_notifications()',
       'EXECUTE'
     )
     or not has_function_privilege(
       'service_role',
       'public.ensure_monthly_checkin_notifications()',
       'EXECUTE'
     ) then
    raise exception 'monthly check-in RPC ACL is incorrect';
  end if;

  v_inserted := public.ensure_monthly_checkin_notifications();
  if v_inserted <> 2 then
    raise exception 'first run should insert only the two newly eligible users; got %', v_inserted;
  end if;

  if (
    select count(*)
    from public.scheduled_notifications
    where notification_type = 'monthly_checkin'
      and status = 'scheduled'
      and scheduled_for > now()
  ) <> 3 then
    raise exception 'expected one pre-existing and two newly scheduled monthly check-ins';
  end if;

  if exists (
    select 1
    from public.scheduled_notifications
    where user_id in (
      'f1000000-0000-4000-8000-000000000003'::uuid,
      'f1000000-0000-4000-8000-000000000004'::uuid,
      'f1000000-0000-4000-8000-000000000006'::uuid
    )
      and notification_type = 'monthly_checkin'
  ) then
    raise exception 'disabled or unreachable users must not receive monthly check-ins';
  end if;

  if (
    select count(*)
    from public.scheduled_notifications
    where user_id in (
      'f1000000-0000-4000-8000-000000000002'::uuid,
      'f1000000-0000-4000-8000-000000000005'::uuid
    )
      and notification_type = 'monthly_checkin'
      and task_id is null
      and status = 'scheduled'
      and timezone('Asia/Tokyo', scheduled_for)::date = v_expected_date
      and timezone('Asia/Tokyo', scheduled_for)::time = time '09:00'
  ) <> 2 then
    raise exception 'eligible users must each receive a 09:00 JST check-in 30 days out';
  end if;

  v_inserted := public.ensure_monthly_checkin_notifications();
  if v_inserted <> 0 then
    raise exception 'second run must be idempotent; got % new rows', v_inserted;
  end if;

  if exists (
    select user_id
    from public.scheduled_notifications
    where notification_type = 'monthly_checkin'
      and status = 'scheduled'
      and scheduled_for > now()
    group by user_id
    having count(*) <> 1
  ) then
    raise exception 'a user must have at most one future scheduled monthly check-in';
  end if;
end;
$regression$;

-- The later email-delivery migration replaces this same function. Reapply
-- after dirty legacy grants and prove it restores the same service-only ACL.
grant execute on function public.ensure_monthly_checkin_notifications() to anon, authenticated;
\ir notification_email_delivery.sql

do $email_acl$
begin
  if has_function_privilege('public', 'public.ensure_monthly_checkin_notifications()', 'EXECUTE')
     or has_function_privilege('anon', 'public.ensure_monthly_checkin_notifications()', 'EXECUTE')
     or has_function_privilege('authenticated', 'public.ensure_monthly_checkin_notifications()', 'EXECUTE')
     or not has_function_privilege('service_role', 'public.ensure_monthly_checkin_notifications()', 'EXECUTE') then
    raise exception 'email-delivery replacement must remove legacy monthly check-in client grants';
  end if;
end;
$email_acl$;

set local role anon;
do $anon_denied$
begin
  begin
    perform public.ensure_monthly_checkin_notifications();
    raise exception 'anon unexpectedly executed the monthly check-in scheduler';
  exception when insufficient_privilege then
    null;
  end;
end;
$anon_denied$;
reset role;

set local role authenticated;
do $authenticated_denied$
begin
  begin
    perform public.ensure_monthly_checkin_notifications();
    raise exception 'authenticated unexpectedly executed the monthly check-in scheduler';
  exception when insufficient_privilege then
    null;
  end;
end;
$authenticated_denied$;
reset role;

set local role service_role;
do $service_allowed$
begin
  if public.ensure_monthly_checkin_notifications() <> 0 then
    raise exception 'service role must retain idempotent monthly scheduling after email migration';
  end if;
end;
$service_allowed$;
reset role;

rollback;
