-- Schedule reminder notifications from task due dates.
-- Run after schema.sql. This works with tasks generated by task_generation.sql.

create or replace function public.schedule_notifications_for_task()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from scheduled_notifications
  where scheduled_notifications.task_id = new.id
    and scheduled_notifications.status = 'scheduled';

  if new.due_date is null or new.status in ('done', 'skipped') then
    return new;
  end if;

  insert into scheduled_notifications (
    user_id,
    task_id,
    scheduled_for,
    status
  )
  select distinct
    family_members.user_id,
    new.id,
    ((new.due_date - 1)::timestamp + time '09:00') at time zone 'Asia/Tokyo',
    'scheduled'
  from people
  join family_members on family_members.family_id = people.family_id
  where people.id = new.person_id
    and family_members.user_id is not null
    and (
      (new.assigned_member_id is not null and family_members.id = new.assigned_member_id)
      or
      (new.assigned_member_id is null and family_members.role in ('owner', 'admin'))
    );

  return new;
end;
$$;

drop trigger if exists trg_schedule_notifications_for_task on tasks;

create trigger trg_schedule_notifications_for_task
after insert or update of due_date, status, assigned_member_id on tasks
for each row
execute function public.schedule_notifications_for_task();

