-- Schedule reminder notifications from task due dates.
-- Run after schema.sql. This works with tasks generated by task_generation.sql.
-- Low-frequency/high-importance policy:
-- - statutory/legal deadline tasks: 14d / 7d / 1d / due day
-- - priority 1 tasks: 7d / 1d
-- - all other tasks: 1d only

create or replace function public.schedule_notifications_for_task()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from scheduled_notifications
  where scheduled_notifications.task_id = new.id
    and scheduled_notifications.status = 'scheduled';

  if new.due_date is null or new.status in ('done', 'skipped') then
    return new;
  end if;

  insert into scheduled_notifications (
    user_id,
    task_id,
    notification_type,
    scheduled_for,
    status
  )
  select distinct
    family_members.user_id,
    new.id,
    reminder.notification_type,
    ((new.due_date - reminder.days_before)::timestamp + time '09:00') at time zone 'Asia/Tokyo',
    'scheduled'
  from people
  join family_members on family_members.family_id = people.family_id
  cross join lateral (
    select *
    from (
      values
        ('due_14d'::text, 14),
        ('due_7d'::text, 7),
        ('due_1d'::text, 1),
        ('due_today'::text, 0)
    ) as reminder(notification_type, days_before)
    where case
      when coalesce(new.category, '') in ('legal_deadline', 'public', 'inheritance')
        or new.title ~ '(死亡届|年金|準確定申告|相続税|相続登記)'
        then reminder.notification_type in ('due_14d', 'due_7d', 'due_1d', 'due_today')
      when coalesce(new.priority, 3) <= 1
        then reminder.notification_type in ('due_7d', 'due_1d')
      else reminder.notification_type = 'due_1d'
    end
  ) reminder
  where people.id = new.person_id
    and family_members.user_id is not null
    and new.due_date - reminder.days_before >= current_date
    and (
      (new.assigned_member_id is not null and family_members.id = new.assigned_member_id)
      or
      (new.assigned_member_id is null and family_members.role in ('owner', 'admin'))
    )
  on conflict (user_id, task_id, notification_type)
  do update set
    scheduled_for = excluded.scheduled_for,
    status = 'scheduled',
    sent_at = null,
    opened_at = null;

  return new;
end;
$$;

drop trigger if exists trg_schedule_notifications_for_task on tasks;

create trigger trg_schedule_notifications_for_task
after insert or update of due_date, status, assigned_member_id on tasks
for each row
execute function public.schedule_notifications_for_task();
